ASP/youtube-develop/ASP.Net Core/LibraryManagement-master/Controllers/LendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LibraryManagement.Data.Interfaces;
using LibraryManagement.ViewModels;
using LibraryManagement.Data.Model;

namespace LibraryManagement.Controllers
{
    public class LendController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly ICustomerRepository _customerRepository;

        public LendController(IBookRepository bookRepository, ICustomerRepository customerRepository)
        {
            _bookRepository = bookRepository;
            _customerRepository = customerRepository;
        }

        public IActionResult List()
        {
            Func<Book, bool> myFilter = x => x.BorrowerId == 0;

            // check collection
            if (!_bookRepository.Any(myFilter))
            {
                return View("Empty");
            }

            // load all available books
            var availableBooks = _bookRepository.FindWithAuthor(myFilter);

            return View(availableBooks);
        }


        public IActionResult LendBook(int bookId)
        {
            var lendVM = new LendViewModel
            {
                Book = _bookRepository.GetById(bookId),
                Customers = _customerRepository.GetAll()
            };

            return View(lendVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult LendBook(LendViewModel lendVM)
        {
            var book = _bookRepository.GetById(lendVM.Book.BookId);

            book.BorrowerId = lendVM.Book.BorrowerId;

            _bookRepository.Update(book);

            return RedirectToAction("List");
        }
    }
}

ASP/youtube-develop/ASP.Net Core/LibraryManagement-master/Controllers/ReturnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using LibraryManagement.Data.Interfaces;
using LibraryManagement.Data.Model;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace LibraryManagement.Controllers
{
    public class ReturnController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly ICustomerRepository _customerRepository;

        public ReturnController(IBookRepository bookRepository, ICustomerRepository customerRepository)
        {
            _bookRepository = bookRepository;
            _customerRepository = customerRepository;
        }

        public IActionResult List()
        {
            Func<Book, bool> myFilter = x => x.BorrowerId != 0;

            // Check the books collection
            if (!_bookRepository.Any(myFilter))
            {
                return View("Empty");
            }

            // load all borrowed books
            var borrowedBooks = _bookRepository.FindWithAuthorAndBorrower(myFilter);

            return View(borrowedBooks);
        }

        public IActionResult ReturnABook(int bookId)
        {
            var book = _bookRepository.GetById(bookId);

            book.Borrower = null;

            book.BorrowerId = 0;

            _bookRepository.Update(book);

            return RedirectToAction("List");
        }
    }
}

ASP/youtube-develop/ASP.Net Core/LibraryManagement-master/Views/Shared/AuthorPartial.cshtml
@model Author

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <p>@Model.Name</p>
        </div>
        <div class="panel-body">
            <h2>Book count: @Model.Books?.Count</h2>
            <div class="btn-group">
                @if (Model.Books?.Count == 0)
                {
                    <a class="btn btn-default" asp-area="">View book list</a>
                }
                else
                {
                   <a class="btn btn-info" asp-area="" asp-controller="Book" asp-action="List" asp-route-authorId="@Model.AuthorId">View book list</a>
                }
                <a class="btn btn-info" asp-area="" asp-controller="Author" asp-action="Update" asp-route-id="@Model.AuthorId">Edit</a>
                <a class="btn btn-danger" asp-area="" asp-controller="Author" asp-action="Delete" asp-route-id="@Model.AuthorId">Delete</a>
            </div>
        </div>
    </div>
</div>

ASP/youtube-develop/ASP.Net Core/LibraryManagement-master/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryManagement</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LibraryManagement</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Customer" asp-action="List">Customers</a></li>
                    <li><a asp-area="" asp-controller="Author" asp-action="List">Authors</a></li>
                    <li><a asp-area="" asp-controller="Author" asp-action="AuthorDetail">AuthorDetail</a></li>
                    <li><a asp-area="" asp-controller="Book" asp-action="List">Books</a></li>
                    <li><a asp-area="" asp-controller="Lend" asp-action="List">Lend a book</a></li>
                    <li><a asp-area="" asp-controller="Return" asp-action="List">Return back</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Library Management by Miroslav Mikus</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>